-- ============================================
-- PetVac Database Setup: Core Tables
-- ============================================

-- 1. PetOwnerProfiles
CREATE TABLE IF NOT EXISTS public."PetOwnerProfiles" (
    id uuid NOT NULL,
    date_registered date NOT NULL DEFAULT CURRENT_DATE,
    last_name character varying NOT NULL,
    first_name character varying NOT NULL,
    gender character varying NULL,
    birth_date date NULL,
    barangay character varying NULL,
    phone_number character varying NOT NULL,
    email text NULL,
    password text NULL,
    CONSTRAINT pet_owner_records_pkey PRIMARY KEY (id),
    CONSTRAINT "PetOwnerProfiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users (id) ON UPDATE CASCADE ON DELETE CASCADE
);

-- 2. PersonnelProfiles
CREATE TABLE IF NOT EXISTS public."PersonnelProfiles" (
    id uuid NOT NULL,
    email text NULL,
    password text NULL,
    last_name text NULL,
    first_name text NULL,
    phone_number text NULL,
    address text NULL,
    CONSTRAINT personnel_profiles_pkey PRIMARY KEY (id),
    CONSTRAINT "PersonnelProfiles_id_fkey" FOREIGN KEY (id) REFERENCES auth.users (id) ON DELETE CASCADE
);

-- 3. VaccineInventory
CREATE TABLE IF NOT EXISTS public."VaccineInventory" (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    batch_number text NOT NULL,
    name text NOT NULL,
    stockin_date date NOT NULL,
    expiration_date date NOT NULL,
    original_qty integer NOT NULL,
    remaining_qty integer NOT NULL,
    status text NOT NULL,
    last_modified timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT vaccine_management_records_pkey PRIMARY KEY (id)
);

-- 4. VaccinationSchedule
CREATE TABLE IF NOT EXISTS public."VaccinationSchedule" (
    id bigint NOT NULL,
    title text NOT NULL,
    start_date date NOT NULL,
    start_time time without time zone NOT NULL,
    end_date date NOT NULL,
    end_time time without time zone NOT NULL,
    location text NOT NULL,
    note text NULL,
    "allDay" boolean NOT NULL DEFAULT true,
    CONSTRAINT vaccine_schedule_pkey PRIMARY KEY (id)
);

-- 5. PetRecords
CREATE TABLE IF NOT EXISTS public."PetRecords" (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    pet_name text NOT NULL,
    specie character varying NOT NULL,
    sex character varying NOT NULL,
    breed character varying NULL,
    birth_date date NOT NULL,
    weight integer NULL,
    color character varying NULL,
    owner_id uuid NOT NULL,
    date_vaccinated date NULL,
    pet_origin text NULL,
    ownership text NULL,
    habitat text NULL,
    tag text NULL,
    is_pregnant boolean NULL,
    num_puppies smallint NULL DEFAULT 0,
    is_lactating_with_puppies boolean NULL,
    CONSTRAINT "PetRecords_pkey" PRIMARY KEY (id),
    CONSTRAINT "PetRecords_owner_id_fkey" FOREIGN KEY (owner_id) REFERENCES public."PetOwnerProfiles" (id) ON UPDATE CASCADE ON DELETE CASCADE
);
