-- ============================================
-- PetVac Database Setup: Relationship Tables
-- ============================================

-- 1. VaccinationRecords
CREATE TABLE IF NOT EXISTS public."VaccinationRecords" (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    vax_sched_id bigint NULL,
    vaccine_id bigint NULL,
    pet_id uuid NULL,
    CONSTRAINT "VaccinationRecords_pkey" PRIMARY KEY (id),
    CONSTRAINT "VaccinationRecords_pet_id_fkey" FOREIGN KEY (pet_id) REFERENCES public."PetRecords" (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT "VaccinationRecords_vaccine_id_fkey" FOREIGN KEY (vaccine_id) REFERENCES public."VaccineInventory" (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT "VaccinationRecords_vax_sched_id_fkey" FOREIGN KEY (vax_sched_id) REFERENCES public."VaccinationSchedule" (id) ON UPDATE CASCADE ON DELETE CASCADE
);

-- 2. AppointmentRecords
CREATE TABLE IF NOT EXISTS public."AppointmentRecords" (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id uuid NULL,
    ticket_num text NULL,
    vaccine_sched_id bigint NULL,
    time time without time zone NULL,
    pet_id uuid NULL,
    status text NULL DEFAULT 'uved'::text,
    CONSTRAINT "AppointmentRecords_pkey" PRIMARY KEY (id),
    CONSTRAINT "AppointmentRecords_owner_id_fkey" FOREIGN KEY (owner_id) REFERENCES public."PetOwnerProfiles" (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT "AppointmentRecords_pet_id_fkey" FOREIGN KEY (pet_id) REFERENCES public."PetRecords" (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT "AppointmentRecords_vaccine_sched_id_fkey" FOREIGN KEY (vaccine_sched_id) REFERENCES public."VaccinationSchedule" (id) ON UPDATE CASCADE ON DELETE CASCADE
);

-- 3. DistributedVaccines
CREATE TABLE IF NOT EXISTS public."DistributedVaccines" (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    inventory_id bigint NOT NULL,
    date date NULL,
    num_vaccines integer NULL,
    barangay text NULL,
    CONSTRAINT "DistributedVaccines_pkey" PRIMARY KEY (id),
    CONSTRAINT "DistributedVaccines_inventory_id_fkey" FOREIGN KEY (inventory_id) REFERENCES public."VaccineInventory" (id) ON UPDATE CASCADE ON DELETE CASCADE
);

-- 4. AdminNotifications
CREATE TABLE IF NOT EXISTS public."AdminNotifications" (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    message text NOT NULL,
    CONSTRAINT "AdminNotifications_pkey" PRIMARY KEY (id)
);
